### ISSUE TITLE
Mindbox Koin instance conflicts with the app Koin instance

### ISSUE THREAD

**Issue by NamtarR** [mindbox-cloud/android-sdk#271]
При попытке инициализации Mindbox в проекте, в котором уже есть Koin, происходит падение, так как `startKoin ` можно вызвать только один раз. Проверять наличие запущенного контейнера в приложении, в которое добавлен Mindbox, а потом загружать свои модули, кажется неправильным для библиотеки, которая должна почти незаметно подключаться к проекту.

Нужно добавить проверку типа:

```
val modules = listOf(appModule, dataModule)
GlobalContext.getKoinApplicationOrNull()
    ?.let { loadKoinModules(modules) }
    ?: startKoin {
        androidContext(context)
        modules(modules)
    }
```

**Comment by vkuznecov-renta** [comment]
Fixed in version 2.2.3
