### ISSUE TITLE
[Android] Нельзя изменить цвет иконки в push для Material You

### ISSUE THREAD

**Issue by CoolyWooly** [mindbox-cloud/android-sdk#367]
Здравствуйте! 
Не могу установить цвет фона иконки уведомления на Andoird 13, т.к. иконки стали векторными и заливаются цветом, а цвет фона иконок (если не задан) берутся по умолчанию из Material You

Просьба добавить в `Mindbox.handleRemoteMessage` метод `setColor`, как у родного `NotificationCompat.Builder`

**Comment by enotniy** [comment]
@CoolyWooly Спасибо, за issue. Действительно, ситуация такая. Рассмотрим возможность добавления такого API в следующую версию.

**Comment by enotniy** [comment]
Добавили [возможность](https://developers.mindbox.ru/docs/%D0%B8%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0-push-%D1%83%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%BC-%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%BC) с версии 2.10.0 менять цвет иконки
