### ISSUE TITLE
App build always failed

### ISSUE THREAD

**Issue by dronn1kDev** [mindbox-cloud/android-sdk#442]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkProdDebugAarMetadata'.
> Could not resolve all files for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:6.5.0.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
       - https://storage.googleapis.com/download.flutter.io/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
     Required by:
         project :app > project :mindbox_android > cloud.mindbox:mindbox-huawei:2.8.4
   > Could not find com.huawei.hms:ads-identifier:3.4.39.302.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
       - https://storage.googleapis.com/download.flutter.io/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
     Required by:
         project :app > project :mindbox_android > cloud.mindbox:mindbox-huawei:2.8.4

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

Flutter doctor output:
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.4 23E214 darwin-arm64, locale en-MD)
    • Flutter version 3.7.12 on channel stable at /Users/dronn1k/flutter/sdk/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (11 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dronn1k/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 14.4 23E214 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by enotniy** [comment]
Hello @dronn1kDev
Thank you for bringing this to our attention. However, it appears there might be a misunderstanding. This repository does not pertain to Flutter development. It seems your issue is more relevant to a different project.

You might be looking for the following repository: [mindbox-cloud/flutter-sdk](https://github.com/mindbox-cloud/flutter-sdk). I would recommend checking there and possibly opening your issue in that repository.

**Comment by dronn1kDev** [comment]
Hello! =)
Thanks for ur reply. I'll make the same issue in flutter sdk repo, but i think the issue is not connected with flutter.
So, should I close the issue in this repo?
